"""add_image_url_to_machines

Revision ID: 028f4c7202fa
Revises: b9b6019bceca
Create Date: 2025-11-13 09:10:47.769418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '028f4c7202fa'
down_revision: Union[str, None] = 'b9b6019bceca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machines', sa.Column('imageUrl', sa.String(length=500), nullable=True))
    op.drop_index('ix_spare_parts_requests_maintenanceWorkId', table_name='spare_parts_requests')
    op.drop_index('ix_spare_parts_requests_requestedBy', table_name='spare_parts_requests')
    op.drop_index('ix_spare_parts_requests_sparePartId', table_name='spare_parts_requests')
    op.drop_index('ix_spare_parts_requests_status', table_name='spare_parts_requests')
    op.create_index(op.f('ix_sparepart_categories_id'), 'sparepart_categories', ['id'], unique=False)
    op.drop_index('ix_spareparts_category_id', table_name='spareparts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_spareparts_category_id', 'spareparts', ['categoryId'], unique=False)
    op.drop_index(op.f('ix_sparepart_categories_id'), table_name='sparepart_categories')
    op.create_index('ix_spare_parts_requests_status', 'spare_parts_requests', ['status'], unique=False)
    op.create_index('ix_spare_parts_requests_sparePartId', 'spare_parts_requests', ['sparePartId'], unique=False)
    op.create_index('ix_spare_parts_requests_requestedBy', 'spare_parts_requests', ['requestedBy'], unique=False)
    op.create_index('ix_spare_parts_requests_maintenanceWorkId', 'spare_parts_requests', ['maintenanceWorkId'], unique=False)
    op.drop_column('machines', 'imageUrl')
    # ### end Alembic commands ###
