"""add_location_field_to_spare_parts

Revision ID: 205d7d00674d
Revises: ff34c2220ba3
Create Date: 2025-10-28 18:06:51.819212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '205d7d00674d'
down_revision: Union[str, None] = 'ff34c2220ba3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spareparts', sa.Column('location', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spareparts', 'location')
    # ### end Alembic commands ###
