"""add_category_number_and_name_to_spare_parts

Revision ID: 2d41713881c0
Revises: 205d7d00674d
Create Date: 2025-10-28 18:31:14.896297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d41713881c0'
down_revision: Union[str, None] = '205d7d00674d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spareparts', sa.Column('categoryNumber', sa.String(length=50), nullable=True))
    op.add_column('spareparts', sa.Column('categoryName', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spareparts', 'categoryName')
    op.drop_column('spareparts', 'categoryNumber')
    # ### end Alembic commands ###
