"""rename_name_to_partname_in_spare_parts

Revision ID: 91bc6459bfe1
Revises: de82bf4a8190
Create Date: 2025-10-28 18:45:24.293179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91bc6459bfe1'
down_revision: Union[str, None] = 'de82bf4a8190'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('spareparts', 'name',
                    new_column_name='partName',
                    existing_type=sa.String(length=200),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('spareparts', 'partName',
                    new_column_name='name',
                    existing_type=sa.String(length=200),
                    nullable=False)
    # ### end Alembic commands ###
