"""update_machines_table_for_qr_codes

Revision ID: b38d29f90445
Revises: f2b013163803
Create Date: 2025-10-26 17:05:26.808410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b38d29f90445'
down_revision: Union[str, None] = 'f2b013163803'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machines', sa.Column('installationDate', sa.Date(), nullable=True))
    op.add_column('machines', sa.Column('status', sa.Enum('OPERATIONAL', 'DOWN', 'MAINTENANCE', 'DECOMMISSIONED', name='machinestatus'), nullable=False))
    op.alter_column('machines', 'qrCode',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_index('ix_machines_serialNumber', table_name='machines')
    op.drop_column('machines', 'isActive')
    op.drop_column('machines', 'lastMaintenanceDate')
    op.drop_column('machines', 'description')
    op.drop_column('machines', 'nextMaintenanceDate')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machines', sa.Column('nextMaintenanceDate', mysql.DATETIME(), nullable=True))
    op.add_column('machines', sa.Column('description', mysql.TEXT(), nullable=True))
    op.add_column('machines', sa.Column('lastMaintenanceDate', mysql.DATETIME(), nullable=True))
    op.add_column('machines', sa.Column('isActive', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.create_index('ix_machines_serialNumber', 'machines', ['serialNumber'], unique=False)
    op.alter_column('machines', 'qrCode',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('machines', 'status')
    op.drop_column('machines', 'installationDate')
    # ### end Alembic commands ###
