"""remove_category_column_from_spare_parts

Revision ID: de82bf4a8190
Revises: 2d41713881c0
Create Date: 2025-10-28 18:41:24.376984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de82bf4a8190'
down_revision: Union[str, None] = '2d41713881c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spareparts', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spareparts', sa.Column('category', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###
